name: checkout-build-run-docker

on:
  push:
    branches:
      - main 
jobs:
  echo:
    runs-on: [self-hosted, linux, x64]
    steps:
      - name: Check out code  
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main

      - name: Make gradlew executable
        run: chmod +x ./gradlew
        
      - name: Clean and Build
        run: ./gradlew clean build

      - name: Run Server with timeout
        run: timeout 60s java -jar build/libs/GithubAction-Demo-0.0.1-SNAPSHOT.jar || true
